import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import Title from '../components/Title';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<Title title='Home'>Home Page 2</Title>

				<Link href='/about'>
					<div
						style={{
							cursor: 'pointer',
							backgroundColor: 'whitesmoke',
							padding: '1rem 2rem',
						}}>
						<p>Redirect to about page</p>
					</div>
				</Link>
			</main>

			<footer className={styles.footer}></footer>
		</div>
	);
}
